#!/bin/bash
# Generates ../extension-firefox/ — the Firefox-loadable copy of this extension.
#
# Why this exists at all: Chrome MV3 *requires* background.service_worker and
# rejects background.scripts; Firefox rejects background.service_worker outright
# ("currently disabled. Add background.scripts."). One manifest.json cannot
# satisfy both. Symlinking the shared files into a second directory does not
# work either — Firefox refuses to read symlinked extension resources (measured:
# the options page never loads). So the Firefox tree needs real files, and this
# script makes them.
#
# extension/ is the single source of truth. Never edit extension-firefox/ —
# it is regenerated (and git-ignored) wholesale.
#
# Usage:  extension/build-firefox.sh        then reload the add-on in Firefox
set -euo pipefail

src="$(cd "$(dirname "$0")" && pwd)"
out="$(dirname "$src")/extension-firefox"

# Shared files. Anything added to the extension must be listed here too.
shared=(background.js content.js options.html options.js icons)

for f in "${shared[@]}" manifest.firefox.json; do
  if [ ! -e "$src/$f" ]; then
    echo "error: missing $src/$f" >&2
    exit 1
  fi
done

# Guard against the two manifests drifting: everything except `background`
# (deliberately different) and the Firefox-only gecko block must match.
if command -v python3 > /dev/null 2>&1; then
  python3 - "$src/manifest.json" "$src/manifest.firefox.json" <<'PY'
import json, sys
chrome, firefox = (json.load(open(p)) for p in sys.argv[1:3])
skip = {"background", "browser_specific_settings"}
drift = [k for k in set(chrome) | set(firefox)
         if k not in skip and chrome.get(k) != firefox.get(k)]
if drift:
    print("warning: manifest.json and manifest.firefox.json disagree on: "
          + ", ".join(sorted(drift)), file=sys.stderr)
    print("         update both, then re-run.", file=sys.stderr)
    sys.exit(1)
PY
fi

rm -rf "$out"
mkdir -p "$out"
for f in "${shared[@]}"; do
  cp -R "$src/$f" "$out/$f"
done
cp "$src/manifest.firefox.json" "$out/manifest.json"

cat > "$out/GENERATED-DO-NOT-EDIT" <<EOF
This directory is generated by extension/build-firefox.sh from extension/.
Edit the sources in extension/ and re-run that script; changes made here are
destroyed on the next build.
EOF

echo "wrote $out (from $src)"
echo "Firefox: about:debugging#/runtime/this-firefox -> Load Temporary Add-on"
echo "         -> $out/manifest.json"
