#!/usr/bin/env python3
"""Invariants of the shipped Defense Trainer board pack.

`static/data/defense-puzzles.json` is generated by
`scripts/mine_defense_puzzles.py` and committed, so nothing at runtime
re-checks it. The game leans on every one of these properties — a bad
regeneration would ship an unplayable or, worse, a subtly wrong board (one
where a "safe" tile wasn't actually safe). These tests are what stands
between that and production.
"""

import json
from pathlib import Path

import pytest

from scripts.mine_defense_puzzles import (
    MAX_FLOW,
    MAX_RIICHI_TURN,
    MIN_FLOW,
    mine_kyoku,
)

PACK = Path(__file__).resolve().parent.parent / "static" / "data" / "defense-puzzles.json"
TILES = set(
    [f"{n}{s}" for s in "mps" for n in range(1, 10)]
    + [f"5{s}r" for s in "mps"]
    + ["E", "S", "W", "N", "P", "F", "C"]
)


@pytest.fixture(scope="module")
def pack():
    return json.loads(PACK.read_text())


def test_pack_is_present_and_populated(pack):
    assert pack["version"] == 1
    assert len(pack["puzzles"]) >= 50


class TestPuzzleShape:
    def test_every_puzzle_is_playable(self, pack):
        for p in pack["puzzles"]:
            assert len(p["ponds"]) == 4
            assert len(p["winds"]) == 4
            assert sorted(p["winds"]) == ["E", "N", "S", "W"]
            # Seat 0 is the replay's own player; you can't defend against
            # your own riichi, so the declarer is always an opponent.
            assert p["seat"] in (1, 2, 3)
            assert 1 <= p["turn"] <= MAX_RIICHI_TURN
            assert MIN_FLOW <= len(p["flow"]) <= MAX_FLOW

    def test_the_riichi_tile_is_the_declarers_last_discard(self, pack):
        """`turn` indexes into the declarer's pond — the game rotates that tile."""
        for p in pack["puzzles"]:
            assert p["turn"] == len(p["ponds"][p["seat"]])

    def test_every_tile_is_valid_mjai_notation(self, pack):
        for p in pack["puzzles"]:
            for pond in p["ponds"]:
                assert all(t in TILES for t in pond)
            assert all(t in TILES for _, t in p["flow"])
            assert all(t in TILES for t in p["dora"])
            assert all(seat in (0, 1, 2, 3) for seat, _ in p["flow"])

    def test_no_duplicate_boards(self, pack):
        keys = {json.dumps(p, sort_keys=True) for p in pack["puzzles"]}
        assert len(keys) == len(pack["puzzles"])


class TestMiner:
    """The two truncations that keep "safe" honest — see the miner's docstring."""

    def _kyoku(self, tail):
        head = {"type": "start_kyoku", "bakaze": "E", "kyoku": 1, "honba": 0,
                "oya": 0, "dora_marker": "1m"}
        # Seat 1 riichi on its first discard, then a long clean flow.
        body = [{"type": "dahai", "actor": 0, "pai": "9m"},
                {"type": "reach", "actor": 1},
                {"type": "dahai", "actor": 1, "pai": "1p"}]
        for i in range(14):
            body.append({"type": "dahai", "actor": (i + 2) % 4, "pai": "5s"})
        return [head] + body + tail

    def test_a_ron_drops_the_winning_tile(self):
        """The tile that was ronned did NOT pass the declarer."""
        clean = mine_kyoku(self._kyoku([{"type": "ryukyoku"}]), player_id=0)
        ron = mine_kyoku(
            self._kyoku([{"type": "hora", "actor": 1, "target": 2, "pai": "5s"}]),
            player_id=0)
        assert len(ron["flow"]) == len(clean["flow"]) - 1

    def test_a_tsumo_keeps_the_whole_flow(self):
        """Nobody's discard won the hand, so every one of them passed."""
        clean = mine_kyoku(self._kyoku([{"type": "ryukyoku"}]), player_id=0)
        tsumo = mine_kyoku(
            self._kyoku([{"type": "hora", "actor": 1, "target": 1, "pai": "5s"}]),
            player_id=0)
        assert len(tsumo["flow"]) == len(clean["flow"])

    def test_a_second_riichi_cuts_the_flow(self):
        """With two declarers, "safe" would mean two different things."""
        head = {"type": "start_kyoku", "bakaze": "E", "kyoku": 1, "honba": 0,
                "oya": 0, "dora_marker": "1m"}
        body = [{"type": "reach", "actor": 1},
                {"type": "dahai", "actor": 1, "pai": "1p"}]
        body += [{"type": "dahai", "actor": 2, "pai": "5s"}] * 11
        body += [{"type": "reach", "actor": 3}]
        body += [{"type": "dahai", "actor": 3, "pai": "9p"}] * 5
        p = mine_kyoku([head] + body + [{"type": "ryukyoku"}], player_id=0)
        assert len(p["flow"]) == 11

    def test_own_riichi_is_skipped(self):
        assert mine_kyoku(self._kyoku([{"type": "ryukyoku"}]), player_id=1) is None

    def test_a_late_riichi_is_skipped(self):
        head = {"type": "start_kyoku", "bakaze": "E", "kyoku": 1, "honba": 0,
                "oya": 0, "dora_marker": "1m"}
        body = [{"type": "dahai", "actor": 1, "pai": "1p"}] * MAX_RIICHI_TURN
        body += [{"type": "reach", "actor": 1},
                 {"type": "dahai", "actor": 1, "pai": "2p"}]
        body += [{"type": "dahai", "actor": 2, "pai": "5s"}] * 12
        assert mine_kyoku([head] + body + [{"type": "ryukyoku"}], player_id=0) is None

    def test_a_short_kyoku_is_skipped(self):
        head = {"type": "start_kyoku", "bakaze": "E", "kyoku": 1, "honba": 0,
                "oya": 0, "dora_marker": "1m"}
        body = [{"type": "reach", "actor": 1},
                {"type": "dahai", "actor": 1, "pai": "1p"}]
        body += [{"type": "dahai", "actor": 2, "pai": "5s"}] * (MIN_FLOW - 1)
        assert mine_kyoku([head] + body + [{"type": "ryukyoku"}], player_id=0) is None

    def test_seats_are_rotated_so_the_replays_player_sits_at_zero(self):
        """player_id 2 -> the declarer at absolute seat 1 lands at relative 3."""
        head = {"type": "start_kyoku", "bakaze": "E", "kyoku": 1, "honba": 0,
                "oya": 1, "dora_marker": "1m"}
        body = [{"type": "dahai", "actor": 2, "pai": "9m"},
                {"type": "reach", "actor": 1},
                {"type": "dahai", "actor": 1, "pai": "1p"}]
        body += [{"type": "dahai", "actor": 3, "pai": "5s"}] * 12
        p = mine_kyoku([head] + body + [{"type": "ryukyoku"}], player_id=2)
        assert p["seat"] == 3                    # (1 - 2) % 4
        assert p["ponds"][0] == ["9m"]           # the replay's own pond
        assert p["ponds"][3] == ["1p"]           # the declarer's
        assert p["winds"][0] == "S"              # seat 2, dealer at seat 1
        assert p["winds"][3] == "E"              # the dealer is the declarer
