#!/usr/bin/env python3
"""Mine Defense Trainer puzzles out of the stored Mortal analyses.

The Defense Trainer (`static/js/defense-trainer.js`) is a client-side
minigame with no API of its own, so its boards ship as a static pack —
`static/data/defense-puzzles.json` — generated by this script and committed.
Re-run it to refresh the pack as more games are uploaded.

A puzzle is one real kyoku in which an opponent declared riichi early, cut
at the declaration:

  * riichi by the declarer's 5th discard (so the starting safe set is small),
  * at least MIN_FLOW discards after the declaration (the game's step count),
  * the riichi is *not* the replay's own player — you can't defend against
    your own riichi.

What the pack stores is deliberately anonymous: seat winds, ponds, the dora
indicator and the discard order. No player names, no game id, no user id —
nothing that ties a board back to the account that uploaded it.

Seats are rotated so index 0 is the replay's player ("You", bottom of the
board) and 1/2/3 go clockwise (shimocha / toimen / kamicha), which is the
seating the trainer renders directly.

Two truncations keep the "safe" set unambiguous, because the game's whole
premise is that every tile discarded after the declaration passed the
declarer:

  * a **ron** ends the flow one tile early — the winning tile did NOT pass;
  * a **second riichi** ends the flow there — with two declarers "safe"
    would mean two different things.

Usage:
    # inside the container, where mortal_analysis/ actually lives
    docker compose exec -T app python3 scripts/mine_defense_puzzles.py --out - \
        > static/data/defense-puzzles.json
"""

import argparse
import hashlib
import json
import sys
from datetime import date
from pathlib import Path

# Riichi no later than the declarer's Nth discard. The declarer's pond at
# declaration is the starting safe set, so this is what keeps step 1 easy.
MAX_RIICHI_TURN = 5
# Discards after the declaration = playable steps. Anything shorter isn't
# worth a round.
MIN_FLOW = 10
# Ponds run past 25 discards; nobody plays a single board that long, and the
# pack has no reason to carry what the game will never show.
MAX_FLOW = 20

WINDS = ["E", "S", "W", "N"]


def flatten(mjai_log):
    """mjai entries may be lists of simultaneous events — flatten to dicts."""
    out = []
    for item in mjai_log or []:
        if isinstance(item, list):
            out.extend(e for e in item if isinstance(e, dict))
        elif isinstance(item, dict):
            out.append(item)
    return out


def split_kyoku(events):
    """Group a flat event stream into one list per kyoku (start_kyoku first)."""
    kyoku, cur = [], None
    for e in events:
        if e.get("type") == "start_kyoku":
            cur = [e]
            kyoku.append(cur)
        elif cur is not None:
            cur.append(e)
    return kyoku


def mine_kyoku(events, player_id):
    """One kyoku -> a puzzle dict, or None when it doesn't qualify."""
    head = events[0]
    oya = head.get("oya")
    if oya is None or player_id is None:
        return None

    dora = head.get("dora_marker")
    dora = list(dora) if isinstance(dora, list) else ([dora] if dora else [])

    ponds = [[], [], [], []]        # absolute seat -> discards, in order
    flow = []                       # (seat, tile) discarded after the riichi
    pending_reach = None            # actor who declared, awaiting their dahai
    riichi_seat = None
    riichi_turn = None

    for e in events[1:]:
        t = e.get("type")
        if t == "reach":
            if riichi_seat is None:
                pending_reach = e.get("actor")
            else:
                break               # a second riichi — cut the flow here
        elif t == "dahai":
            actor, pai = e.get("actor"), e.get("pai")
            if riichi_seat is None:
                ponds[actor].append(pai)
                if pending_reach == actor:
                    riichi_seat, riichi_turn = actor, len(ponds[actor])
                    pending_reach = None
            else:
                flow.append([actor, pai])
                if len(flow) >= MAX_FLOW:
                    break
        elif t == "hora":
            # A ron's winning tile did not pass the declarer: drop it.
            if e.get("actor") != e.get("target") and flow:
                flow.pop()
            break
        elif t == "ryukyoku":
            break

    if riichi_seat is None or riichi_seat == player_id:
        return None
    if riichi_turn > MAX_RIICHI_TURN or len(flow) < MIN_FLOW:
        return None

    # Rotate so the replay's player sits at index 0 and 1/2/3 run clockwise.
    def rel(seat):
        return (seat - player_id) % 4

    rel_ponds = [None] * 4
    for seat in range(4):
        rel_ponds[rel(seat)] = ponds[seat]
    # Seat wind = distance from the dealer, in the same rotated order.
    winds = [WINDS[(player_id + i - oya) % 4] for i in range(4)]

    return {
        "bakaze": head.get("bakaze", "E"),
        "kyoku": head.get("kyoku", 1),
        "honba": head.get("honba", 0),
        "winds": winds,
        "dora": dora,
        "seat": rel(riichi_seat),
        "turn": riichi_turn,
        "ponds": rel_ponds,
        "flow": [[rel(seat), pai] for seat, pai in flow],
    }


def mine_file(path):
    try:
        data = json.loads(Path(path).read_text())
    except (OSError, ValueError):
        return []
    events = flatten(data.get("mjai_log"))
    player_id = data.get("player_id")
    out = []
    for kyoku in split_kyoku(events):
        puzzle = mine_kyoku(kyoku, player_id)
        if puzzle:
            out.append(puzzle)
    return out


def puzzle_key(p):
    """Stable content hash — dedupes re-uploads and orders the pack."""
    blob = json.dumps(p, sort_keys=True, separators=(",", ":"))
    return hashlib.sha1(blob.encode()).hexdigest()


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--logs", default="mortal_analysis",
                    help="directory of Mortal analysis JSON files")
    ap.add_argument("--out", default="static/data/defense-puzzles.json",
                    help="output path, or - for stdout")
    ap.add_argument("--limit", type=int, default=0,
                    help="keep at most N puzzles (0 = all)")
    args = ap.parse_args()

    files = sorted(Path(args.logs).glob("*.json"))
    by_key = {}
    for f in files:
        for p in mine_file(f):
            by_key.setdefault(puzzle_key(p), p)

    # Hash order: stable across runs, but not grouped by game, so consecutive
    # puzzles in a run don't all come from the same table.
    puzzles = [by_key[k] for k in sorted(by_key)]
    if args.limit:
        puzzles = puzzles[:args.limit]

    pack = {
        "version": 1,
        "generated": date.today().isoformat(),
        "source_games": len(files),
        "puzzles": puzzles,
    }
    blob = json.dumps(pack, separators=(",", ":"))
    if args.out == "-":
        sys.stdout.write(blob)
    else:
        Path(args.out).parent.mkdir(parents=True, exist_ok=True)
        Path(args.out).write_text(blob)
        print(f"{len(puzzles)} puzzles from {len(files)} games -> {args.out}",
              file=sys.stderr)


if __name__ == "__main__":
    main()
